/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayShift;

public class ArrayShift {

    public  int[] ArrayShift(int[] array, int val){


        int[] newArray = new int[array.length + 1];
        int middlePointindex = 0;

        if(array.length % 2 == 0)
        {
            middlePointindex = array.length/ 2;

        }
        else
        {
            middlePointindex = (array.length+1)/ 2;

        }

        for(int i = 0; i < newArray.length; i++)
        {
            if (i < middlePointindex)
            {
                newArray[i] = array[i];
            }
            else if(i == middlePointindex)
            {
                newArray[i] = val;
            }
            else
            {
                newArray[i] = array[i - 1];
            }


        }
        return newArray;

    }
}
