/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarySearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testExsistIndex() {
        Library classUnderTest = new Library();
        int[] nums = { 4, 8, 15, 16, 23, 42 };
        int key = 15;
        assertEquals("should give you the index of the key in the array back",2,classUnderTest.binarySearch(nums,key));
    }


    @Test public void testNotExistsIndex() {
        Library classUnderTest = new Library();
        int[] nums = { 4, 8, 15, 16, 23, 42 };
        int key = 99;
        assertEquals("should give you  back -1 because it not exsits",-1,classUnderTest.binarySearch(nums,key));
    }

    @Test public void testOneNumArray() {
        Library classUnderTest = new Library();
        int[] nums = {4};
        int key = 4;
        assertEquals("should give you the index of the key in the array back",0,classUnderTest.binarySearch(nums,key));
    }

}
