/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arrayShift;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testRegularEvenNumberArray() {
        Library lOne = new Library();
        int[] inputArr =new int[] {2,4,6,8};
        int[] expectedArr =new int[] {2,4,5,6,8};
        assertArrayEquals(expectedArr, lOne.ArrayShift(inputArr,5));
    }


    @Test
    public void testRegularOddNumberArray(){
        Library lOne = new Library();
        int[] inputArr =new int[] {2,4,5,6,8};
        int[] expectedArr =new int[] {2,4,5,35,6,8};
        assertArrayEquals(expectedArr, lOne.ArrayShift(inputArr,35));
    }

    @Test
    public void testOneNumberArray(){
        Library lOne = new Library();
        int[] inputArr =new int[] {2};
        int[] expectedArr =new int[] {2,4};
        assertArrayEquals(expectedArr, lOne.ArrayShift(inputArr,4));
    }


    @Test
    public void testNullArray(){
        Library lOne = new Library();
        int[] inputArr =new int[] {};
        int[] expectedArr =new int[] {2};
        assertArrayEquals(expectedArr, lOne.ArrayShift(inputArr,2));
    }

}
